# Generated by Django 5.0.4 on 2024-05-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_Name',
            new_name='CustomerName',
        ),
    ]
