# Generated by Django 5.0.4 on 2024-05-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0002_rename_customer_name_customer_customername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='contract_manager',
            new_name='manager',
        ),
    ]
