# Generated by Django 5.0.4 on 2024-05-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0003_rename_contract_manager_assignment_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='manager',
            new_name='contract_manager',
        ),
    ]
