# Generated by Django 5.0.4 on 2024-05-30 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0004_rename_manager_assignment_contract_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receiver', models.CharField(max_length=100)),
                ('Workplace', models.CharField(max_length=100)),
                ('Order_items', models.CharField(max_length=1000)),
                ('Order_time', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_smartwork_app.assignment')),
            ],
        ),
    ]
