# Generated by Django 5.0.4 on 2024-05-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Sender',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
