# Generated by Django 5.0.4 on 2024-05-30 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0007_remove_order_assignment_order_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='assignment',
        ),
        migrations.AddField(
            model_name='order',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_smartwork_app.assignment'),
            preserve_default=False,
        ),
    ]
