# Generated by Django 5.0.4 on 2024-05-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0009_remove_order_assignment_order_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='assignment',
        ),
    ]
