# Generated by Django 5.0.4 on 2024-05-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0011_alter_order_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Receiver',
            field=models.CharField(max_length=100),
        ),
    ]
