# Generated by Django 5.0.4 on 2024-06-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0013_order_order_status_order_time_alter_order_order_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender', models.CharField(max_length=100)),
                ('Receiver', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=1000000)),
                ('Sendingtime', models.CharField(max_length=100)),
            ],
        ),
    ]
