# Generated by Django 5.0.6 on 2024-06-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0014_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='Image',
            field=models.ImageField(default=1, upload_to='conversation/Images'),
            preserve_default=False,
        ),
    ]
