# Generated by Django 5.0.6 on 2024-06-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0015_conversation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='Image',
            field=models.ImageField(blank=True, upload_to='conversation/Images'),
        ),
    ]
